server:
  port: 8082
  servlet:
    contextPath: /buyMyBag
spring:
  datasource:
    password: Diablerouge98
    username : root
    url: jdbc:mysql://localhost:3306/shopping_website_db?serverTimezone=UTC&useLegacyDatetimeCode=false