server:
  port: 8082
  servlet:
    contextPath: /buyMyBag
spring:
  datasource:
    password: BuyMyBag69
    username : root
    url: jdbc:mysql://buymybag.ck8e4ot53w8k.eu-central-1.rds.amazonaws.com:3306/website_shop_db?serverTimezone=UTC&useLegacyDatetimeCode=false